services:
  - type: web
    name: empanada-delivery-web
    runtime: ruby
    buildCommand: |
      bundle install
      npm ci
      npm run build
      bundle exec rails assets:precompile
      bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: empanada-delivery-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: empanada-delivery-redis
          type: redis
          property: connectionString

  - type: worker
    name: empanada-delivery-worker
    runtime: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -q high -q default -q low
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: empanada-delivery-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: empanada-delivery-redis
          type: redis
          property: connectionString

databases:
  - name: empanada-delivery-db
    plan: free

  - name: empanada-delivery-redis
    type: redis
    plan: free
